title: Full Stack Web Developer
author: Barry Halper
lead: A highly motivated full-stack web developer with over twenty years of commercial experience, delivering market-leading business-to-business brands
live_site_path: http://barryhalper.com.servepreview.net


twitter: https://www.twitter.com/barryhalper
linked_in: https://www.linkedin.com/in/barry-halper
email: me@barryhalper.com
github: https://www.github.com/barryhalper